language: python
python:
  - "3.6"      # current default Python on Travis CI
  - "3.7"
  - "3.8"

# command to install package
install:
  - pip install -e .
  - pip install coverage

# command to run tests
script:
  - pytest tests/unit/ --cov datacaster

after_success:
  - bash <(curl -s https://codecov.io/bash)
